"""Initial schema

Revision ID: 197abcab2512
Revises: 
Create Date: 2026-05-12 17:18:57.909978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197abcab2512'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute('CREATE SCHEMA IF NOT EXISTS tests_schema')
    op.execute('CREATE SCHEMA IF NOT EXISTS users_schema')

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users_schema'
    )
    op.create_index(op.f('ix_users_schema_users_email'), 'users', ['email'], unique=True, schema='users_schema')
    op.create_index(op.f('ix_users_schema_users_nickname'), 'users', ['nickname'], unique=True, schema='users_schema')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=256), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('test_title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tests_schema'
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=256), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('first_answer', sa.String(length=256), nullable=False),
    sa.Column('second_answer', sa.String(length=256), nullable=False),
    sa.Column('third_answer', sa.String(length=256), nullable=False),
    sa.Column('fourth_answer', sa.String(length=256), nullable=False),
    sa.Column('right_answer', sa.Integer(), nullable=False),
    sa.Column('test_title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tests_schema'
    )
    op.create_table('user_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_title', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),

    sa.ForeignKeyConstraint(['user_id'], ['users_schema.users.user_id'], ondelete='CASCADE'),

    sa.PrimaryKeyConstraint('id'),

    schema='tests_schema'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_schema_users_nickname'), table_name='users', schema='users_schema')
    op.drop_index(op.f('ix_users_schema_users_email'), table_name='users', schema='users_schema')
    op.drop_table('users', schema='users_schema')
    op.drop_table('tests', schema='tests_schema')
    op.drop_table('test_cards', schema='tests_schema')
    op.drop_table('user_results', schema='tests_schema')
    op.execute('DROP SCHEMA IF EXISTS tests_schema')
    op.execute('DROP SCHEMA IF EXISTS users_schema')
    # ### end Alembic commands ###
