"""Add test_cards indexes

Revision ID: 56db704a23fc
Revises: 197abcab2512
Create Date: 2026-06-01 23:06:35.008077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56db704a23fc'
down_revision: Union[str, Sequence[str], None] = '197abcab2512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('idx_profession_course', 'test_cards', ['profession', 'course'], unique=False, schema='tests_schema')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profession_course', table_name='test_cards', schema='tests_schema')
    # ### end Alembic commands ###
