"""Add average score column in users table

Revision ID: f78058530c81
Revises: 56db704a23fc
Create Date: 2026-06-02 15:00:25.823820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78058530c81'
down_revision: Union[str, Sequence[str], None] = '56db704a23fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('average_score', sa.Float(), nullable=True), schema='users_schema')
    op.create_index(op.f('ix_users_schema_users_average_score'), 'users', ['average_score'], unique=False, schema='users_schema')
    op.create_index(op.f('ix_users_schema_users_group'), 'users', ['group'], unique=False, schema='users_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_schema_users_group'), table_name='users', schema='users_schema')
    op.drop_index(op.f('ix_users_schema_users_average_score'), table_name='users', schema='users_schema')
    op.drop_column('users', 'average_score', schema='users_schema')
    # ### end Alembic commands ###
